name: Run modloader runtime test
description: Executes headlesshq/mc-runtime-test and performs required cleanup between loader runs.

inputs:
  loader-type:
    description: Mod loader type (forge|neoforge|fabric)
    required: true
  minecraft-version:
    description: Minecraft version
    required: true
  modloader-regex:
    description: Regex to match the modloader jar
    required: true
  java-version:
    description: Java version for mc-runtime-test
    required: false
    default: '21'
  mc-runtime-test-type:
    description: mc-runtime-test jar to download (none|lexforge|neoforge|fabric). If empty, derived from loader-type.
    required: false
    default: ''
  fabric-api-version:
    description: Fabric API version to download (or none)
    required: false
    default: 'none'
  headlessmc-command:
    description: Extra HeadlessMC command args
    required: false
    default: '--jvm "-Djava.awt.headless=true"'
  cache-mc:
    description: Cache strategy for .minecraft folder (github|blacksmith|true|false)
    required: false
    default: 'github'
  needs-vanilla-cleanup:
    description: If true, deletes $HOME/.minecraft/versions after the test
    required: false
    default: 'false'

outputs:
  status:
    description: success|failure
    value: ${{ steps.status.outputs.status }}

runs:
  using: composite
  steps:
    - name: Ensure $HOME/.minecraft exists
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$HOME/.minecraft"

    - name: Derive mc-runtime-test type
      id: mcrt
      shell: bash
      run: |
        set -euo pipefail
        mcrt="${{ inputs.mc-runtime-test-type }}"
        if [[ -z "$mcrt" ]]; then
          case "${{ inputs.loader-type }}" in
            forge) mcrt="lexforge" ;;
            neoforge) mcrt="neoforge" ;;
            fabric) mcrt="fabric" ;;
            *)
              echo "ERROR: unsupported loader-type=${{ inputs.loader-type }}" >&2
              exit 1
              ;;
          esac
        fi
        echo "mc_runtime_test=$mcrt" >> "$GITHUB_OUTPUT"

    - name: Validate Minecraft version exists
      shell: bash
      run: |
        set -euo pipefail
        mc="${{ inputs.minecraft-version }}"
        if ! command -v curl >/dev/null 2>&1; then
          echo "ERROR: curl is required to validate minecraft-version=${mc}. Install curl on the runner." >&2
          exit 1
        fi

        # Fail fast on obvious typos like 1.21.11 (not a real Minecraft release).
        manifest_url="https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"
        if command -v jq >/dev/null 2>&1; then
          if ! curl -fsSL "$manifest_url" | jq -e --arg mc "$mc" '.versions | any(.id == $mc)' >/dev/null; then
            echo "ERROR: minecraft-version '${mc}' not found in Mojang version manifest." >&2
            echo "This usually means your gradle.properties minecraft_version is wrong (example: 1.21.11 vs 1.21.1)." >&2
            exit 1
          fi
        else
          # Fallback for minimal runners: normalize whitespace so a fixed-string match works.
          if ! curl -fsSL "$manifest_url" | tr -d '\n\r\t ' | grep -Fq "\"id\":\"${mc}\""; then
            echo "ERROR: minecraft-version '${mc}' not found in Mojang version manifest." >&2
            echo "This usually means your gradle.properties minecraft_version is wrong (example: 1.21.11 vs 1.21.1)." >&2
            exit 1
          fi
        fi

    - name: Guard against stale vanilla-only version cache
      shell: bash
      run: |
        set -euo pipefail
        mc="${{ inputs.minecraft-version }}"
        loader="${{ inputs.loader-type }}"
        vanilla_json="$HOME/.minecraft/versions/${mc}/${mc}.json"

        if [[ ! -f "$vanilla_json" ]]; then
          exit 0
        fi

        # headlesshq/mc-runtime-test only runs the HeadlessMC download/install commands
        # when the vanilla JSON is missing. If the vanilla JSON exists but the loader
        # profile doesn't, force the action to re-run download/install.
        case "$loader" in
          fabric)
            shopt -s nullglob
            candidates=("$HOME/.minecraft/versions/fabric-loader-"*"-${mc}")
            if [[ ${#candidates[@]} -eq 0 ]]; then
              echo "Detected vanilla version JSON but no Fabric loader profile; forcing re-download/install" >&2
              rm -f "$vanilla_json"
            fi
            ;;
          forge)
            shopt -s nullglob
            candidates=("$HOME/.minecraft/versions/forge-"*"-${mc}")
            if [[ ${#candidates[@]} -eq 0 ]]; then
              echo "Detected vanilla version JSON but no Forge loader profile; forcing re-download/install" >&2
              rm -f "$vanilla_json"
            fi
            ;;
          neoforge)
            shopt -s nullglob
            candidates=("$HOME/.minecraft/versions/neoforge-"*"-${mc}")
            if [[ ${#candidates[@]} -eq 0 ]]; then
              echo "Detected vanilla version JSON but no NeoForge loader profile; forcing re-download/install" >&2
              rm -f "$vanilla_json"
            fi
            ;;
          *)
            echo "ERROR: unsupported loader-type=${loader}" >&2
            exit 1
            ;;
        esac

    - name: Validate mc-runtime-test asset exists (pinned release)
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        mc="${{ inputs.minecraft-version }}"
        mcrt="${{ steps.mcrt.outputs.mc_runtime_test }}"
        tag="4.1.0"

        if ! command -v curl >/dev/null 2>&1; then
          echo "ERROR: curl is required to validate mc-runtime-test assets." >&2
          exit 1
        fi

        api_url="https://api.github.com/repos/headlesshq/mc-runtime-test/releases/tags/${tag}"
        json="$(curl -fsSL \
          -H "Authorization: Bearer ${GH_TOKEN}" \
          -H "Accept: application/vnd.github+json" \
          "$api_url")"

        # mc-runtime-test downloads an asset like:
        #   mc-runtime-test-<mc>-*-<mcrt>-release.jar
        # For example:
        #   mc-runtime-test-1.21.1-*-fabric-release.jar
        asset_regex="\"name\"[[:space:]]*:[[:space:]]*\"mc-runtime-test-${mc}-.*-${mcrt}-release\\.jar\""
        if ! echo "$json" | grep -Eq "$asset_regex"; then
          echo "ERROR: headlesshq/mc-runtime-test@${tag} has no asset matching mc-runtime-test-${mc}-*-${mcrt}-release.jar" >&2
          echo "This means the MC version is unsupported by the pinned runtime-test release, or minecraft-version is wrong." >&2
          exit 1
        fi

    - name: Run MC runtime test
      id: run
      uses: headlesshq/mc-runtime-test@4.1.0
      with:
        mc: ${{ inputs.minecraft-version }}
        modloader: ${{ inputs.loader-type }}
        regex: ${{ inputs.modloader-regex }}
        java: ${{ inputs.java-version }}
        mc-runtime-test: ${{ steps.mcrt.outputs.mc_runtime_test }}
        fabric-api: ${{ inputs.fabric-api-version }}
        headlessmc-command: ${{ inputs.headlessmc-command }}
        cache-mc: ${{ inputs.cache-mc }}

    - name: Cleanup .minecraft/versions
      if: always() && inputs.needs-vanilla-cleanup == 'true'
      shell: bash
      run: |
        set -euo pipefail
        if [[ -d "$HOME/.minecraft/versions" ]]; then
          rm -rf "$HOME/.minecraft/versions"
        fi

    - name: Set status output
      id: status
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${{ steps.run.outcome }}" == "success" ]]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
        fi
