name: Run modloader runtime test
description: Executes headlesshq/mc-runtime-test and performs required cleanup between loader runs.

inputs:
  loader-type:
    description: Mod loader type (forge|neoforge|fabric)
    required: true
  minecraft-version:
    description: Minecraft version
    required: true
  artifact-regex:
    description: Regex to match the mod jar staged in ./run/mods
    required: true
  java-version:
    description: Java version for mc-runtime-test
    required: false
    default: '21'
  mc-runtime-test-type:
    description: mc-runtime-test jar to download (none|lexforge|neoforge|fabric). If empty, derived from loader-type.
    required: false
    default: ''
  fabric-api-version:
    description: Fabric API version to download (or none)
    required: false
    default: 'none'
  headlessmc-command:
    description: Extra HeadlessMC command args
    required: false
    default: '--jvm "-Djava.awt.headless=true"'
  cache-mc:
    description: Cache strategy for .minecraft folder (github|blacksmith|true|false)
    required: false
    default: 'github'
  needs-vanilla-cleanup:
    description: If true, deletes $HOME/.minecraft/versions after the test
    required: false
    default: 'false'

outputs:
  status:
    description: success|failure
    value: ${{ steps.status.outputs.status }}

runs:
  using: composite
  steps:
    - name: Ensure $HOME/.minecraft exists
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$HOME/.minecraft"

    - name: Derive mc-runtime-test type
      id: mcrt
      shell: bash
      run: |
        set -euo pipefail
        mcrt="${{ inputs.mc-runtime-test-type }}"
        if [[ -z "$mcrt" ]]; then
          case "${{ inputs.loader-type }}" in
            forge) mcrt="lexforge" ;;
            neoforge) mcrt="neoforge" ;;
            fabric) mcrt="fabric" ;;
            *)
              echo "ERROR: unsupported loader-type=${{ inputs.loader-type }}" >&2
              exit 1
              ;;
          esac
        fi
        echo "mc_runtime_test=$mcrt" >> "$GITHUB_OUTPUT"

    - name: Run MC runtime test
      id: run
      uses: headlesshq/mc-runtime-test@4.1.0
      with:
        mc: ${{ inputs.minecraft-version }}
        modloader: ${{ inputs.loader-type }}
        regex: ${{ inputs.artifact-regex }}
        java: ${{ inputs.java-version }}
        mc-runtime-test: ${{ steps.mcrt.outputs.mc_runtime_test }}
        fabric-api: ${{ inputs.fabric-api-version }}
        headlessmc-command: ${{ inputs.headlessmc-command }}
        cache-mc: ${{ inputs.cache-mc }}

    - name: Cleanup .minecraft/versions
      if: always() && inputs.needs-vanilla-cleanup == 'true'
      shell: bash
      run: |
        set -euo pipefail
        if [[ -d "$HOME/.minecraft/versions" ]]; then
          rm -rf "$HOME/.minecraft/versions"
        fi

    - name: Set status output
      id: status
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${{ steps.run.outcome }}" == "success" ]]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
        fi
