name: Build + Test + Runtime Test
on:
  push:
  pull_request:

jobs:
  build:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-build.yml@main
    with:
      project-root: .
      gradle-args: build
      runs-on: ubuntu-latest

      # Same-run artifact handoff: upload jars for later jobs.
      upload-artifacts: true
      # artifact-name: 1.21.1-0.1.0  # Optional override; defaults to ${minecraft_version}-${mod_version}

  test:
    needs: build
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-test.yml@main
    with:
      project-root: .
      gradle-args: test
      runs-on: ubuntu-latest

  runtime-test:
    needs: [build, test]
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-runtime-test.yml@main
    with:
      project-root: .

      # Same-run artifact handoff: download jars and skip Gradle build.
      use-build-artifacts: true
      # artifact-name: 1.21.1-0.1.0  # Optional override; defaults to ${minecraft_version}-${mod_version}

      # Still required for the workflow interface, but ignored when use-build-artifacts=true.
      gradle-args: build

      # Optional: choose how runtime dependencies are sourced.
      # runtime-deps-mode: dependencies-yml  # default
      # runtime-deps-mode: metadata-min
      # runtime-deps-mode: metadata-max
      # runtime-deps-mode: none

      cache-mc: github
      runs-on: self-hosted
