name: Build
on:
  push:
  pull_request:

jobs:
  build:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-build.yml@main
    with:
      project-root: .
      java-version: '21'
      gradle-args: build
