name: Build + Test + Runtime Test
on:
  push:
  pull_request:

jobs:
  build:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-build.yml@main
    with:
      project-root: .
      gradle-args: build
      runs-on: ubuntu-latest

      # Same-run artifact handoff: upload jars for later jobs.
      upload-artifacts: true
      artifact-name: build-artifacts

  test:
    needs: build
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-test.yml@main
    with:
      project-root: .
      gradle-args: test
      runs-on: ubuntu-latest

  runtime-test:
    needs: [build, test]
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-runtime-test.yml@main
    with:
      project-root: .

      # Same-run artifact handoff: download jars and skip Gradle build.
      use-build-artifacts: true
      artifact-name: build-artifacts

      # Still required for the workflow interface, but ignored when use-build-artifacts=true.
      gradle-args: build

      cache-mc: github
      runs-on: self-hosted
