name: Build
on:
  push:
  pull_request:

jobs:
  build:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-build.yml@main
    with:
      project-root: .
      gradle-args: build
      runs-on: ubuntu-latest

      # Optional (same-run artifact handoff): upload jars for later jobs.
      # upload-artifacts: true
      # artifact-name: build-artifacts
