name: Runtime Test
on:
  workflow_dispatch:

jobs:
  runtime-test:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-runtime-test.yml@main
    with:
      project-root: .
      gradle-args: build

      # Optional: choose how runtime dependencies are sourced.
      # runtime-deps-mode: dependencies-yml  # default
      # runtime-deps-mode: metadata-min
      # runtime-deps-mode: metadata-max
      # runtime-deps-mode: none

      # Optional (same-run artifact handoff): download jars and skip Gradle build.
      # use-build-artifacts: true
      # artifact-name: 1.21.1-0.1.0  # Optional override; defaults to ${minecraft_version}-${mod_version}

      cache-mc: github
      runs-on: self-hosted
