name: Runtime Test
on:
  workflow_dispatch:

jobs:
  runtime-test:
    uses: XxInvictus/mc_universal_workflow/.github/workflows/reusable-runtime-test.yml@main
    with:
      project-root: .
      gradle-args: build

      # Optional (same-run artifact handoff): download jars and skip Gradle build.
      # use-build-artifacts: true
      # artifact-name: build-artifacts

      cache-mc: github
      runs-on: self-hosted
